export const Erros = {
	NOME_VAZIO: "NOME_VAZIO",
	NOME_PEQUENO: "NOME_PEQUENO",
	ID_INVALIDO: "ID_INVALIDO",
	EMAIL_INVALIDO: "EMAIL_INVALIDO",
	DESCONHECIDO: "DESCONHECIDO",
	NOME_SEM_SOBRENOME: "NOME_SEM_SOBRENOME",
	NOME_GRANDE: "NOME_GRANDE",
	NOME_CARACTERES_INVALIDOS: "NOME_CARACTERES_INVALIDOS",
} as const;
